---
- import_tasks: amzn2.yml
  when:
    - ansible_distribution == "Amazon"
    - ansible_service_mgr == "systemd"

- import_tasks: el7.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
